remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one









#theme: jekyll-theme-Architect
#title: Michael Elizondo
#description: >
  #Sr. Systems Engineer 路 Enterprise Cloud 路 DevOps 路 DevSecOps 路 Application Security
#github:
  #is_project_page: false
