remote_theme: pages-themes/architect@v0.2.0
title: Michael Elizondo
description: Technology Executive 路 Enterprise Cloud 路 DevOps 路 DevSecOps 路 Application Security 
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one. This is just a test


# TESTING 
